#pragma once

// Includes all Structures
#include "Agridome.h"
#include "AirShaft.h"
#include "CHAP.h"
#include "ColonistLander.h"
#include "CommandCenter.h"
#include "Commercial.h"
#include "FusionReactor.h"
#include "Laboratory.h"
#include "MedicalCenter.h"
#include "MineFacility.h"
#include "MineShaft.h"
#include "Park.h"
#include "Police.h"
#include "RecreationCenter.h"
#include "RedLightDistrict.h"
#include "Residence.h"
#include "RobotCommand.h"
#include "SeedFactory.h"
#include "SeedLander.h"
#include "SeedPower.h"
#include "SeedSmelter.h"
#include "Smelter.h"
#include "SolarPlant.h"
#include "StorageTanks.h"
#include "SurfaceFactory.h"
#include "Tube.h"
#include "UndergroundFactory.h"
#include "University.h"
#include "Warehouse.h"

