#pragma once

// Includes all Structures
#include "Agridome.h"
#include "AirShaft.h"
#include "CHAP.h"
#include "CommandCenter.h"
#include "FusionReactor.h"
#include "MineFacility.h"
#include "MineShaft.h"
#include "Residence.h"
#include "SeedFactory.h"
#include "SeedLander.h"
#include "SeedPower.h"
#include "SeedSmelter.h"
#include "Smelter.h"
#include "StorageTanks.h"
#include "SurfaceFactory.h"
#include "Tube.h"
#include "UndergroundFactory.h"
