version: 2.1

commands:
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    steps:
      - run: make --directory nas2d-core/ install-dependencies
  build:
    steps:
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" nas2d
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" ophd
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" testLibOPHD
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" testLibControls
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" checkOPHD
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" checkControls

jobs:
  build-macos:
    macos:
      xcode: "26.5"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: git submodule update --init nas2d-core/
      - brew-install
      - build

workflows:
  build:
    jobs:
      - build-macos
