#pragma once

// Includes all Structures
#include "Structures/Agridome.h"
#include "Structures/CargoLander.h"
#include "Structures/ColonistLander.h"
#include "Structures/CommandCenter.h"
#include "Structures/CommTower.h"
#include "Structures/HotLaboratory.h"
#include "Structures/Laboratory.h"
#include "Structures/MaintenanceFacility.h"
#include "Structures/MineFacility.h"
#include "Structures/MineShaft.h"
#include "Structures/OreRefining.h"
#include "Structures/Recycling.h"
#include "Structures/Residence.h"
#include "Structures/Road.h"
#include "Structures/SeedFactory.h"
#include "Structures/SeedLander.h"
#include "Structures/StorageTanks.h"
#include "Structures/SurfaceFactory.h"
#include "Structures/Tube.h"
#include "Structures/UndergroundFactory.h"
#include "Structures/Warehouse.h"
